# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 7) do

  create_table "accessories", :force => true do |t|
    t.column "name",         :text
    t.column "description",  :text
    t.column "price",        :integer
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
    t.column "outofstock",   :boolean,  :default => false
    t.column "discontinued", :boolean,  :default => false
  end

  create_table "features", :force => true do |t|
    t.column "name",        :text
    t.column "description", :text
    t.column "created_at",  :datetime
    t.column "updated_at",  :datetime
  end

  create_table "phones", :force => true do |t|
    t.column "name",         :text
    t.column "description",  :text
    t.column "outright",     :integer
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
    t.column "outofstock",   :boolean,  :default => false
    t.column "discontinued", :boolean,  :default => false
  end

  create_table "phones_accessories", :id => false, :force => true do |t|
    t.column "phone_id",     :integer, :null => false
    t.column "accessory_id", :integer, :null => false
  end

  add_index "phones_accessories", ["phone_id", "accessory_id"], :name => "index_phones_accessories_on_phone_id_and_accessory_id"

  create_table "phones_features", :id => false, :force => true do |t|
    t.column "phone_id",   :integer, :null => false
    t.column "feature_id", :integer, :null => false
  end

  add_index "phones_features", ["phone_id", "feature_id"], :name => "index_phones_features_on_phone_id_and_feature_id"

  create_table "phones_plans", :id => false, :force => true do |t|
    t.column "plan_id",     :integer,                :null => false
    t.column "phone_id",    :integer,                :null => false
    t.column "offer_price", :integer, :default => 0
  end

  add_index "phones_plans", ["phone_id", "plan_id"], :name => "index_phones_plans_on_phone_id_and_plan_id"

  create_table "plans", :force => true do |t|
    t.column "name",         :text
    t.column "comments",     :text
    t.column "price",        :integer
    t.column "flexi_code",   :text
    t.column "flexi_price",  :integer
    t.column "base_etc",     :integer
    t.column "offer",        :text
    t.column "contract",     :integer
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
    t.column "discontinued", :boolean,  :default => false
  end

end
